# YOLOv8 Dataset Configuration - New Barefeet Dataset

# Absolute path to the dataset directory
path: C:/Users/VitalSign/Documents/4in1-vital-sign/backend/ai_camera/datasets_barefeet

# Subfolders for images
train: train/images
val: valid/images
test: test/images

# Classes
nc: 1
names: 
  0: 'bare_feet'
